function zi = interp2(x,y,z,xi,yi,method)
% TOMSYM/INTERP2 - overloaded function
%
% ZI = INTERP2(X,Y,Z,XI,YI) interpolates Z to find ZI.
%
% ZI = INTERP2(X,Y,Z,XI,YI,METHOD) specifies the method to use.
%
% X, Y and Z must be numeric. Only XI and YI are currently implemented as
% tomSym variables.
%
% Extrapolation is currently handled differently as compared to the
% standard Matlab function. The same method is used for both interpolation
% and extrapolation. This may change in the future. It is recommended to
% use a larger table and interpolate, rather than to extrapolate.

% Per Rutquist, Tomlab Optimization Inc, E-mail: tomlab@tomopt.com
% Copyright (c) 2010 by Tomlab Optimization Inc.
% Last modified 2010-09-17 by rutquist for TOMLAB release 7.7


if nargin<6
    method = 'linear';
end
if method(1) == 'c'
    method = 'v5cubic';
end
if ~all(size(xi)==size(yi))
    error('XI and YI sizes mismatch');
end

if numel(x) > size(x)
    % Matrix: reduce to a vector
    if ~all(size(x)==size(z))
        error('X matrix dimensions missmatch.');
    end
    if ~all(diff(x,1,1)==0)
        error('X must be regular (as if generated by meshdrid).');
    end
    x = x(1,:);
end
if numel(y) > size(y)
    if ~all(size(y)==size(z))
        error('Y matrix dimensions missmatch.');
    end
    if ~all(diff(y,1,2)==0)
        error('Y must be regular (as if generated by meshdrid).');
    end
    y = y(:,1);
end

if isnumeric(x) && isnumeric(y) && isnumeric(z)
    PPN = interpnpp(method, z', x, y);
    zi = tomSym('ppnval', size(xi,1), size(xi,2), PPN, xi, yi);
else
    error('Not all variations of interp2 have been implemented for tomSym yet.');
end

