% copyexfiles 
%
% Script for copying files needed by the example.

files  = {'DefPar.m', ...
          'LineParamDef.m', ...
          'LineParamSet.m', ...
          'PrintResult.m', ...
          'ProbCheck.m', ...
          'ProbDef.m', ...
          'ResultDef.m', ...
          'SOLGet.m', ...
          'checkType.m', ...
          'cplex.m', ...
          'cplexTL.m', ...
          'cpx2cbinfo.m', ...
          'cpx2retvec.m', ...
          'defblbu.m', ...
          'endSolve.m', ...
          'iniSolve.m', ...
          'mkbound.m', ...
          'optParamDef.m', ...
          'optParamSet.m', ...
          'qpAssign.m', ...
          'qp_H.m', ...
          'qp_f.m', ...
          'qp_g.m', ...
          'snoptTL.m', ...
          'tomFiles.m', ...
          'tomRun.m', ...
          'tomlabVersion.m', ...
          'xnargin.m', ...
          'xnargout.m', ...
          'cplexmex'};

nrfiles = length(files);

for i=1:nrfiles
    disp(['Copying file: ' files{i}]);
    status = copyfile(which(files{i}), '.');
    if(status == 0)
        disp(['Failed to copy file: ' files{i}]);
    end
end