% askgui(action)

% Kenneth Holmstrom, Tomlab Optimization Inc., E-mail: tomlab@tomopt.com.
% Copyright (c) 1997-2005 by Tomlab Optimization Inc., Sweden. $Release: 4.7.0$
% Written Mar 15, 1997.  Last modified Sep 10, 1999.

function askgui(action)

nargin;

global askfig GUIanswer

global question answer instruction 

if strcmp(action,'askquest')
askfig.fig1 = figure('Color',[0.8 0.8 0.8], ...
	'Name','ASKGUI - User defined questions for test problems', ...
	'NumberTitle','off', ...
	'Position',[255 142 515 509], ...
	'Tag','Fig1');
	%'Position',[55 42 715 509], ...

askfig.axes1 = axes('Parent',askfig.fig1, ...
	'Units','points', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Position',[29.25 100.5 317.25 261], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);

askfig.EditText33 = uicontrol('Parent',askfig.fig1, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[65.25 160.00 225.75 20.00], ...
	'FontSize',12, ...
	'Style','edit', ...
	'Tag','EditText33', ...
	'Visible','on');
	%'HorizontalAlignment','left', ...
	%'Max',20, ...
askfig.Pushbutton9 = uicontrol('Parent',askfig.fig1, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[241.5 130.00 48.75 26.25], ...
	'Callback','askgui(''ansquest'');', ...
	'String','OK', ...
	'Tag','Pushbutton9', ...
	'Visible','on');

askfig.StaticText99 = uicontrol('Parent',askfig.fig1, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[65.25 240.00 225.75  60.00], ...
	'FontSize',12, ...
	'String','Diff', ...
	'Style','text', ...
	'Tag','StaticText99', ...
	'Visible','on');
	%'BackgroundColor',[0.752941 0.752941 0.752941], ...

set(gca,'Visible','on')

if ~isempty(instruction) 
   str=str2mat(instruction,question);
else
   str=question;
end 
set(askfig.StaticText99,'max',size(instruction,1))
set(askfig.StaticText99,'String',instruction)

set(askfig.EditText33,'String',question)

set(askfig.StaticText99,'Visible','on')
set(askfig.EditText33,'Visible','on')
uiwait
end

if strcmp(action,'ansquest')
   str=get(askfig.EditText33,'String');
   n=length(question);
   k=findstr(question(1:n),str);
   answer=str(k+n:end);
   uiresume
   close(gcf)
end
